# travis configuration file

language: java

jdk:
- oraclejdk8
- oraclejdk9
- oraclejdk10

sudo: required 

services:
- docker

# Initialize Docker

before_install:
- cd docker/dev
- docker-compose up -d

# Build Projet and test it

script:
- cd ../../src
- mvn test -Ptest-consumer,test-business
- cd ../docker/dev
- docker-compose stop
- docker-compose rm -f
- docker-compose up -d
- cd ../../src

notifications:
email: false
