language: java

jdk:
- openjdk8

sudo: required

services:
- docker

before_install:
- cd docker/dev
- docker-compose up -d

script:
- cd ../../src
- mvn test -Ptest-consumer,test-business
- cd ../docker/dev
- docker-compose stop
- docker-compose rm -f
- docker-compose up -d
- cd ../../src


after_success:
- mvn --file pom.xml cobertura:cobertura coveralls:report -P test-consumer,test-business

notifications:
email: false
